Add sqlite3 so transaction isolation can be activated
This fixes the following error:

NoMethodError:
  undefined method `isolation_level' for ActiveRecord::Base:Class
 # ./lib/lev/routine.rb:394:in `in_transaction'
 # ./lib/lev/routine.rb:236:in `call'
 # ./lib/lev/routine.rb:200:in `call'
 # ./spec/create_sprocket_spec.rb:6:in `block (2 levels) in <top (required)>'